// <auto-generated />
using System;
using BlockChain.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlockChain.Domain.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241107204204_Blocks_table")]
    partial class Blocks_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlockChain.Domain.Models.DataBase.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("BlockId")
                        .HasColumnType("integer")
                        .HasColumnName("block_id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("CurHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cur_hash")
                        .HasAnnotation("Relational:JsonPropertyName", "current_hash");

                    b.Property<bool>("GenesisBlock")
                        .HasColumnType("boolean")
                        .HasColumnName("is_genesis")
                        .HasAnnotation("Relational:JsonPropertyName", "is_genesis");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prev_hash")
                        .HasAnnotation("Relational:JsonPropertyName", "prev_hash");

                    b.Property<int>("ValidCount")
                        .HasColumnType("integer")
                        .HasColumnName("valid_count")
                        .HasAnnotation("Relational:JsonPropertyName", "valid_count");

                    b.HasKey("Id");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("BlockChain.Domain.Models.DataBase.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("CoinsCollected")
                        .HasColumnType("integer")
                        .HasColumnName("coins")
                        .HasAnnotation("Relational:JsonPropertyName", "coins");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.Property<string>("curlId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("curl_id")
                        .HasAnnotation("Relational:JsonPropertyName", "curlid");

                    b.Property<string>("hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash")
                        .HasAnnotation("Relational:JsonPropertyName", "hach");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
